import { query, mutation } from '../_generated/server'
import { listRondasDefinition, getRondaDefinition, getRondaByCodigoDefinition } from './rondas'
import { listParticipantesDefinition, listParticipantesRondaResumenDefinition, listDirectorioParticipantesDefinition } from './participantes'
import { listResultadosDefinition, listResultadosRondaDefinition } from './resultados'
import { listPTItemsDefinition, listPTSampleGroupsDefinition, listEnviosPTRoundDefinition, listAllEnviosPTDefinition } from './pt'
import { getFichaByIdDefinition, getFichaByRondaParticipanteDefinition, getFichaResumenByRondaParticipanteDefinition } from './fichas'
import { getPanelSgcDefinition, getPlanRondaDefinition, getRevisionDatosDefinition, listHitosRondaDefinition, listEvidenciaSeriesDefinition, listEvidenciaVersionesDefinition, listAuditLogDefinition, listSnapshotsDefinition, listComunicacionesDefinition, listPublicacionesDefinition, getDownloadUrlDefinition } from './sgc'
import { createRondaDefinition, createConfiguredRondaDefinition, updateRondaEstadoDefinition, updateRondaConfigDefinition, updateRondaBasicInfoDefinition, deleteRondaDefinition, addContaminanteDefinition, addParticipanteDefinition, updateParticipanteAdminDefinition, removeParticipanteDefinition, createPTItemDefinition, createPTItemsBulkDefinition, createPTSampleGroupDefinition } from './mutations'
import { createOrUpdatePlanRondaDefinition, finalizarPlanRondaDefinition, createOrUpdateRevisionDatosDefinition, finalizarRevisionDatosDefinition, createHitoRondaDefinition, updateHitoRondaDefinition, createEvidenciaSeriesDefinition, registrarEvidenciaVersionDefinition, retirarEvidenciaVersionDefinition, upsertJustificacionDefinition, retirarJustificacionDefinition, createComunicacionDefinition, updateComunicacionDefinition, deleteComunicacionDefinition, createPublicacionDefinition, deletePublicacionDefinition, inicializarPanelSgcDefinition, transitionRondaToDocumentacionPendienteDefinition, transitionRondaToCerradaDefinition, reabrirRondaSgcDefinition } from './sgcMutations'

export const listRondas = query({ ...listRondasDefinition })
export const getRonda = query({ ...getRondaDefinition })
export const getRondaByCodigo = query({ ...getRondaByCodigoDefinition })
export const listParticipantes = query({ ...listParticipantesDefinition })
export const listParticipantesRondaResumen = query({ ...listParticipantesRondaResumenDefinition })
export const listDirectorioParticipantes = query({ ...listDirectorioParticipantesDefinition })
export const listResultados = query({ ...listResultadosDefinition })
export const listResultadosRonda = query({ ...listResultadosRondaDefinition })
export const listPTItems = query({ ...listPTItemsDefinition })
export const listPTSampleGroups = query({ ...listPTSampleGroupsDefinition })
export const listEnviosPTRound = query({ ...listEnviosPTRoundDefinition })
export const listAllEnviosPT = query({ ...listAllEnviosPTDefinition })
export const getFichaById = query({ ...getFichaByIdDefinition })
export const getFichaByRondaParticipante = query({ ...getFichaByRondaParticipanteDefinition })
export const getFichaResumenByRondaParticipante = query({ ...getFichaResumenByRondaParticipanteDefinition })
export const getPanelSgc = query({ ...getPanelSgcDefinition })
export const getPlanRonda = query({ ...getPlanRondaDefinition })
export const getRevisionDatos = query({ ...getRevisionDatosDefinition })
export const listHitosRonda = query({ ...listHitosRondaDefinition })
export const listEvidenciaSeries = query({ ...listEvidenciaSeriesDefinition })
export const listEvidenciaVersiones = query({ ...listEvidenciaVersionesDefinition })
export const listAuditLog = query({ ...listAuditLogDefinition })
export const listSnapshots = query({ ...listSnapshotsDefinition })
export const listComunicaciones = query({ ...listComunicacionesDefinition })
export const listPublicaciones = query({ ...listPublicacionesDefinition })
export const getDownloadUrl = query({ ...getDownloadUrlDefinition })
export const createRonda = mutation({ ...createRondaDefinition })
export const createConfiguredRonda = mutation({ ...createConfiguredRondaDefinition })
export const updateRondaEstado = mutation({ ...updateRondaEstadoDefinition })
export const updateRondaConfig = mutation({ ...updateRondaConfigDefinition })
export const updateRondaBasicInfo = mutation({ ...updateRondaBasicInfoDefinition })
export const deleteRonda = mutation({ ...deleteRondaDefinition })
export const addContaminante = mutation({ ...addContaminanteDefinition })
export const addParticipante = mutation({ ...addParticipanteDefinition })
export const updateParticipanteAdmin = mutation({ ...updateParticipanteAdminDefinition })
export const removeParticipante = mutation({ ...removeParticipanteDefinition })
export const createPTItem = mutation({ ...createPTItemDefinition })
export const createPTItemsBulk = mutation({ ...createPTItemsBulkDefinition })
export const createPTSampleGroup = mutation({ ...createPTSampleGroupDefinition })
export const createOrUpdatePlanRonda = mutation({ ...createOrUpdatePlanRondaDefinition })
export const finalizarPlanRonda = mutation({ ...finalizarPlanRondaDefinition })
export const createOrUpdateRevisionDatos = mutation({ ...createOrUpdateRevisionDatosDefinition })
export const finalizarRevisionDatos = mutation({ ...finalizarRevisionDatosDefinition })
export const createHitoRonda = mutation({ ...createHitoRondaDefinition })
export const updateHitoRonda = mutation({ ...updateHitoRondaDefinition })
export const createEvidenciaSeries = mutation({ ...createEvidenciaSeriesDefinition })
export const registrarEvidenciaVersion = mutation({ ...registrarEvidenciaVersionDefinition })
export const retirarEvidenciaVersion = mutation({ ...retirarEvidenciaVersionDefinition })
export const upsertJustificacion = mutation({ ...upsertJustificacionDefinition })
export const retirarJustificacion = mutation({ ...retirarJustificacionDefinition })
export const createComunicacion = mutation({ ...createComunicacionDefinition })
export const updateComunicacion = mutation({ ...updateComunicacionDefinition })
export const deleteComunicacion = mutation({ ...deleteComunicacionDefinition })
export const createPublicacion = mutation({ ...createPublicacionDefinition })
export const deletePublicacion = mutation({ ...deletePublicacionDefinition })
export const inicializarPanelSgc = mutation({ ...inicializarPanelSgcDefinition })
export const transitionRondaToDocumentacionPendiente = mutation({ ...transitionRondaToDocumentacionPendienteDefinition })
export const transitionRondaToCerrada = mutation({ ...transitionRondaToCerradaDefinition })
export const reabrirRondaSgc = mutation({ ...reabrirRondaSgcDefinition })
