import { query, mutation } from '../_generated/server'
import { getRondaDefinition, getRondaByCodigoDefinition, listRondasDefinition, listParticipantesDefinition, listParticipantesRondaResumenDefinition, getParticipanteRondaResumenDefinition, listRondasParticipanteDefinition, listAllParticipantesDefinition, isInvitadoDefinition } from './reads'
import { listDirectorioParticipantesDefinition, getDirectorioParticipanteByLookupDefinition, upsertDirectorioParticipanteDefinition } from './directorio_definitions'
import { listEnviosDefinition, getEstadoEnvioParticipanteDefinition, listResultadosDefinition, listResultadosRondaDefinition, claimParticipanteTokenDefinition, upsertEnvioDefinition } from './resultados'
import { createRondaDefinition, updateRondaEstadoDefinition, addContaminanteDefinition, addParticipanteDefinition, updateParticipanteAdminDefinition, createConfiguredRondaDefinition, updateRondaConfigDefinition, updateRondaBasicInfoDefinition, transitionRondaEstadoDefinition, reabrirRondaDefinition, assignParticipanteDefinition, regenerateParticipanteSlotDefinition, updateParticipanteEmailDefinition, addReferenceSlotDefinition } from './mutations'
import { deleteRondaDefinition, removeParticipanteDefinition } from './cleanup'

export const getRonda = query({ ...getRondaDefinition })
export const getRondaByCodigo = query({ ...getRondaByCodigoDefinition })
export const listRondas = query({ ...listRondasDefinition })
export const listParticipantes = query({ ...listParticipantesDefinition })
export const listDirectorioParticipantes = query({ ...listDirectorioParticipantesDefinition })
export const getDirectorioParticipanteByLookup = query({ ...getDirectorioParticipanteByLookupDefinition })
export const upsertDirectorioParticipante = mutation({ ...upsertDirectorioParticipanteDefinition })
export const listParticipantesRondaResumen = query({ ...listParticipantesRondaResumenDefinition })
export const getParticipanteRondaResumen = query({ ...getParticipanteRondaResumenDefinition })
export const listRondasParticipante = query({ ...listRondasParticipanteDefinition })
export const listAllParticipantes = query({ ...listAllParticipantesDefinition })
export const isInvitado = query({ ...isInvitadoDefinition })
export const listEnvios = query({ ...listEnviosDefinition })
export const getEstadoEnvioParticipante = query({ ...getEstadoEnvioParticipanteDefinition })
export const listResultados = query({ ...listResultadosDefinition })
export const listResultadosRonda = query({ ...listResultadosRondaDefinition })
export const claimParticipanteToken = mutation({ ...claimParticipanteTokenDefinition })
export const upsertEnvio = mutation({ ...upsertEnvioDefinition })
export const createRonda = mutation({ ...createRondaDefinition })
export const updateRondaEstado = mutation({ ...updateRondaEstadoDefinition })
export const addContaminante = mutation({ ...addContaminanteDefinition })
export const addParticipante = mutation({ ...addParticipanteDefinition })
export const updateParticipanteAdmin = mutation({ ...updateParticipanteAdminDefinition })
export const createConfiguredRonda = mutation({ ...createConfiguredRondaDefinition })
export const updateRondaConfig = mutation({ ...updateRondaConfigDefinition })
export const updateRondaBasicInfo = mutation({ ...updateRondaBasicInfoDefinition })
export const transitionRondaEstado = mutation({ ...transitionRondaEstadoDefinition })
export const reabrirRonda = mutation({ ...reabrirRondaDefinition })
export const deleteRonda = mutation({ ...deleteRondaDefinition })
export const assignParticipante = mutation({ ...assignParticipanteDefinition })
export const regenerateParticipanteSlot = mutation({ ...regenerateParticipanteSlotDefinition })
export const updateParticipanteEmail = mutation({ ...updateParticipanteEmailDefinition })
export const removeParticipante = mutation({ ...removeParticipanteDefinition })
export const addReferenceSlot = mutation({ ...addReferenceSlotDefinition })
