import { notFound } from 'next/navigation'
import { getPtCase, getPtVerificationCandidates, getRonda } from '@/server/rondas'
import { linkVerificationAction, reviewCaseAction } from '../actions'

export default async function AdminCaseDetail({ params }: { params: Promise<{ id: string; casoId: string }> }) {
  const { id, casoId } = await params
  const [ronda, data] = await Promise.all([getRonda(id), getPtCase(casoId).catch(() => null)])
  if (!ronda || !data?.admin || String(data.caso.rondaId) !== id) notFound()
  const candidates = await Promise.all(data.verifications.map(check => getPtVerificationCandidates(casoId, check.ptScoreOrigenId)))
  const originsById = new Map(data.origins.map(origin => [String(origin!._id), origin!]))
  const completed = data.verifications.filter(check => check.resultado === 'satisfactorio').length
  return <main className="mx-auto max-w-5xl space-y-6 px-6 py-8">
    <a className="text-sm text-blue-700" href={`/dashboard/rondas/${id}/casos`}>← Casos</a><div><h1 className="text-3xl font-bold">{data.caso.codigo}</h1><p>{data.caso.titulo}</p></div>
    <section className="card p-5"><h2 className="font-semibold">Documentos recibidos</h2><div className="mt-3 space-y-3">{data.documents.map(document => <div className="rounded-lg border p-3" key={document._id}><strong>{document.categoria.replaceAll('_', ' ')}</strong>{document.versiones.map(version => <div className="text-sm" key={version._id}>v{version.version} · <a className="text-blue-700 underline" href={`/dashboard/rondas/${id}/casos/${casoId}/documentos/${version._id}`}>{version.nombreArchivo}</a> · {version.estado}</div>)}</div>)}</div></section>
    <section className="card p-5"><h2 className="font-semibold">Mensajes</h2>{data.messages.map(message => <div className="mt-2 rounded bg-slate-50 p-3 text-sm" key={message._id}><strong>{message.autorTipo}</strong><p>{message.texto}</p></div>)}</section>
    {data.caso.estado === 'en_revision' && <form action={reviewCaseAction.bind(null, id, casoId)} className="card grid gap-3 p-5"><h2 className="font-semibold">Decisión documental</h2><textarea className="input min-h-24" name="observacion" required placeholder="Observación obligatoria"/><div className="flex gap-2"><button className="btn-outline" name="decision" value="ajustes">Solicitar ajustes</button><button className="btn-primary" name="decision" value="aceptar">Aceptar documentación</button></div></form>}
    <section className="card p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold">Verificación de eficacia</h2><p className="text-sm text-slate-500">Cada resultado origen requiere una comprobación posterior satisfactoria.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm">{completed}/{data.verifications.length} completas</span></div>{data.verifications.map((check, index) => { const origin = originsById.get(String(check.ptScoreOrigenId)); return <div className="mt-3 rounded-lg border p-4 text-sm" key={check._id}><div className="flex flex-wrap justify-between gap-2"><div><strong>{origin?.item?.contaminante ?? 'Resultado'} · {origin?.item?.nivel ?? 'Sin nivel'} · {origin?.metodo ?? 'Sin método'}</strong><p className="text-slate-500">Origen no satisfactorio</p></div><span className={check.resultado === 'satisfactorio' ? 'text-emerald-700' : check.resultado === 'no_satisfactorio' ? 'text-red-700' : 'text-amber-700'}>{check.resultado.replaceAll('_', ' ')} · {check.vinculacion ?? 'sin vínculo'}</span></div>{check.posterior && <p className="mt-2 rounded bg-slate-50 p-2">Resultado posterior: {check.posterior.rondaCodigo} · {check.posterior.contaminante} · {check.posterior.nivel} · {check.posterior.metodo} · {check.posterior.clasificacion.replaceAll('_', ' ')}</p>}{check.resultado !== 'satisfactorio' && <form action={linkVerificationAction.bind(null, id, casoId, check.ptScoreOrigenId)} className="mt-3 grid gap-2"><select className="input" name="posterior_id" required><option value="">Seleccione resultado posterior publicado</option>{candidates[index].map(candidate => <option key={candidate.scoreId} value={candidate.scoreId}>{candidate.rondaCodigo} · {candidate.contaminante} · {candidate.nivel} · {candidate.metodo} · {candidate.clasificacion}</option>)}</select><input className="input" name="motivo" required placeholder="Justificación del vínculo manual"/><button className="btn-outline w-fit">Vincular y evaluar</button></form>}</div> })}</section>
  </main>
}
